### ISSUE TITLE
Noteable updates in v2.6.

### ISSUE THREAD

**Issue by evil-morfar** [SafeteeWoW/RCLootCouncil_EPGP#1]
Just a small heads up to some breaking changes in the next version.

I changed the structure of the CONFIRM_AWARD popup. All functions in this popup are now instantiated on the RCLootCouncilML module so they can be easily hooked (see [the bottom of ml_core](https://github.com/evil-morfar/RCLootCouncil2/blob/2.6.0-Beta1/ml_core.lua#L835)) - this way you shouldn't need to change your code when I make changes. Furthermore I changed the data structure of the table getting delivered to those functions: all values are now named, so the order no longer matters - [an example of the change](https://github.com/evil-morfar/RCLootCouncil2/blob/2.6.0-Beta1/Modules/votingFrame.lua#L1032).

Finally the addition of relic buttons have led to some changes in all "GetResponseXXX", as well as a restructuring of ML:Award() - not that these should matter too much for you. Here's all [changes](https://github.com/evil-morfar/RCLootCouncil2/compare/2.5.5-Release...master) from last release.

I plan 2.6 to release in a weeks time.

**Comment by SafeteeWoW** [comment]
Thanks for the headup.

I have done the fixes to make this plugin supports v2.6.
But I am close to finish a new feature that I started to work on several weeks ago and I want to release the new feature together with the support to v2.6.
The earliest time I think I can release the new version RCLootCouncil-EPGP is probably next Monday.


I am not going to use RCLootCouncilML.AwardPopupOnClickYes, instead, I am going to use
 ~~~~
LibDialog.delegates["RCLOOTCOUNCIL_CONFIRM_AWARD"].buttons[1].on_click
~~~~ 
to provide backward compatibility to RCLootCouncil v2.5. If you solve the problem below, I will use RCLootCouncilML.AwardPopupOnXXX and give up the backward compatibility.

The remaining problem is how to hook the way you pass argument to the dialog.

~~~~
local funcRCLootCouncil_Spawn_RCLOOTCOUNCIL_CONFIRM_AWARD
-- the original award function.
for _, entry in pairs(RCVotingFrame.rightClickEntries[1]) do
    if entry.text == L["Award"] then
        funcRCLootCouncil_Spawn_RCLOOTCOUNCIL_CONFIRM_AWARD = entry.func
        break
    end
end

 -- Get the original input of dialog, inside the click function of a rightclick entry
local dialogInput = {}
RCEPGP:RawHook(LibDialog, "Spawn", function(self, ref, data)
    for key, value in pairs(data) do
        dialogInput[key] = value
    end
end)
funcRCLootCouncil_Spawn_RCLOOTCOUNCIL_CONFIRM_AWARD(name, data)
RCEPGP:Unhook(LibDialog, "Spawn")

dialogInput.gp = gp
dialogInput.responseGP = responseGP
LibDialog:Spawn("RCEPGP_CONFIRM_AWARD", dialogInput)
~~~~

Although this is a very ugly way to get the RCLootCouncil argument to the dialog. But it works and I will no longer need to make any changes even if you have updated the arguments. It also provides backwards compatibility.

To avoid this, you need to add a separate function in RCLootCouncil to return  the table argument of the statement that spawns RCLOOTCOUNCIL_CONFIRM_AWARD dialog.
~~~~
function(name, data)
	LibDialog:Spawn("RCLOOTCOUNCIL_CONFIRM_AWARD", {
		session 		= session,
	  	winner		= name,
		responseID	= data.response,
		reason		= nil,
		votes			= data.votes,
		gear1 		= data.gear1,
		gear2			= data.gear2,
		isTierRoll	= data.isTier,
		isRelicRoll	= data.isRelic,
		link 			= lootTable[session].link,
		isToken		= lootTable[session].token,
	})
end
~~~~
For the above code in votingFrame.lua, you should put the table in a separate function that receives "data"(and probably "session" and "name") as the argument and returns the above table.
If you do that, I will no longer use those ugly hooks and no longer provide backward compatibility to RCLootCouncil v2.5

**Comment by SafeteeWoW** [comment]
I suggest you also make a small change to RCLootCouncil:ChatCommand(msg)
Line 427, core.lua
~~~~
local input, arg1, arg2 = self:GetArgs(msg,3)
~~~~
Line 537, core.lua
~~~~
for k, v in pairs(self.customChatCmd) do
	if k == input then return v.module[v.func](v.module, arg1, arg2) end
end
~~~~

So only two arguments are sent to the custom chat commands functions.
However, I am adding a new command that needs 6 additional arguments.
So I am rawhooking the ChatCommand function to solve this problem right now.

I suggest you to use a loop and self:GetArgs(msg, 1, startPos) to get all arguments and store them in a table. For example, (untested)
~~~~
--- Line 427
local args = {}
local arg, startpos = nil, 1
repeat
    arg, startpos = self:GetArgs(msg, 1, startpos)
    if arg and startPos > 1 then -- Exclude the first arg, because it is command.
         table.insert(args, arg) 
    end
until arg == nil

-- Line 537
for k, v in pairs(self.customChatCmd) do
	if k == input then return v.module[v.func](v.module, unpack(args)) end
end
~~~

**Comment by evil-morfar** [comment]
I see why having direct access to the data makes sense - but honestly all you're trying to do is pack some of your own data into it, and since you're already utilizing the original on_show and on_click functions, done someting like:

```lua
 -- Button 1
     func = function(name, data)
        RCEPGP:SecureHook(RCLootCouncilML, "AwardPopupOnShow", "myOnShowFunc")
        funcRCLootCouncil_Spawn_RCLOOTCOUNCIL_CONFIRM_AWARD(name, data)
        RCEPGP:UnHook(RCLootCouncilML, "AwardPopupOnShow")
     end,

function RCEPGP:myOnShowFunc(frame,data)
   -- extract the data you wanted to pack earlier
   local _, _, _, responseGP, gp, bid = GetGPInfo(name)
   -- Do the stuff you want to do
   -- And probably hook the buttons as well (or do it above)
end
```

Eitherway, that was just my original intention. A new commit [adds the requested](https://github.com/evil-morfar/RCLootCouncil2/commit/3352b7e3ad2bf3a691a77777e426b4cbb8f869fe) function (although untested at the time of writing) and I'll also do another beta version since I have some other changes as well.

As for the chat commands arguments, [done](https://github.com/evil-morfar/RCLootCouncil2/commit/651507a79b970c1a3096e6d244c78a27b08bb7b8)

**Comment by evil-morfar** [comment]
Also, looking over your code I noticed your dynamic right click stuff. Did you ever find out if `Lib_UiDropDownMenu_Refresh` recreates the menu? If so, you could just call that everytime you have changes (on incoming responses?) and register your texts as functions (which I updated my handler to accept).

**Comment by SafeteeWoW** [comment]
I definitely want to do less hooking. Code is so buggy when there is hooks everywhere. 
I have considered sth like your thought:
~~~~
 -- Button 1
        RCEPGP:SecureHook(RCLootCouncilML, "AwardPopupOnShow", "myOnShowFunc")
     func = function(name, data)

        funcRCLootCouncil_Spawn_RCLOOTCOUNCIL_CONFIRM_AWARD(name, data)
        --RCEPGP:UnHook(RCLootCouncilML, "AwardPopupOnShow")
     end,

function RCEPGP:myOnShowFunc(frame,data)
   -- extract the data you wanted to pack earlier
   local _, _, _, responseGP, gp, bid = GetGPInfo(name)
   -- Do the stuff you want to do
   -- And probably hook the buttons as well (or do it above)
end
~~~~
But how can I differ whether the user is clicking a original RCLootCouncil award button or the first award button added by RCLootCouncil-EPGP or the second award button added by RCLootCouncil-EPGP?
Some addition code requires to make it work.

Anyway, direct access to the data solves all the problem.

---
Unfortunately, Lib_UIDropDownMenu_Refresh does not recreate the menu completely. It only refresh  the width of the menu according to the current text content, if menu.noResize is false.

Calling Lib_UIDropDownMenu_Refresh does not call the text function and the text function is only called when the menu opens.

I do hope there is a better solution.

---

I will soon take advantage of  your changes to get rid of those hooks in the code. Still working on the new feature. Hopefully done in several days.

**Comment by evil-morfar** [comment]
Well some hooks are unavoidable, but there's a couple of places where you could avoid them:
* votingUtils line 66: session switches are relayed with Ace-Event messages ("RCSessionChangedPre" or "RCSessionChangedPost")
* votingUtils line 792: Instead of hooking SendChatCommand, you could just subscribe to the RCLootCouncil comms and get it from there.

**Comment by SafeteeWoW** [comment]
+ votingUtils line 66: session switches are relayed with Ace-Event messages ("RCSessionChangedPre" or "RCSessionChangedPost")

This definitely will be changed. This was there just to offer backward compatibility to the earlier version of RCLootCouncil v2.5. I think in the future, I will try to only get rid of backward compatibility when you do a v0.1 update.

---

+ votingUtils line 792: Instead of hooking SendChatCommand, you could just subscribe to the RCLootCouncil comms and get it from there.

I use hook here due to the following reasons.
~~~~
on_click = function(self, data)
    currentAwardingGP = data and data.gp or 0
    LibDialog.delegates["RCLOOTCOUNCIL_CONFIRM_AWARD"].buttons[1].on_click(self, data) -- GP award is happening in this line by a posthook to RCLootCouncil:SendCommand
    currentAwardingGP = 0
end
~~~~
I am using the local variable ```currentAwardingGP``` to store the current GP value being awarded. ```currentAwardingGP``` is set before the original on_click and reset to 0 immediately after (Reset is to ensure ```currentAwardingGP``` is always 0 when the user is clicking the original RCLootCouncil award button to ensure no GP is awarded when clicking on that button, without modifying the func of the button.).

---
Currently, when I use posthook to SendCommand, the code execution order is similar to this:
~~~~
currentAwardingGP = data and data.gp or 0
on_click()
      SendCommand("awarded",...)  
      -- Immediately after, due to post hook
      Award GP by currentAwardingGP
end
currentAwardingGP = 0
~~~~

---
If I register the comm, the execution order will be sth like this:
```
currentAwardingGP = data and data.gp or 0
on_click()
      SendCommand("awarded",...)  
end
currentAwardingGP = 0

OnCommReceived() -- executed after currentAwardingGP is reseted.
                               --  And potentially very late due to commuciation network latency.
      Award GP by currentAwardingGP -- Awarding 0 GP here.
end
```
This is not what I want.

---
To make sure no GP is awarded mistakenly, even when the communication channel is lag, the user uses both RCLootCouncil-EPGP award button and RCLootCOuncil Award Button, or the user open several award dialogs at the same time, I choose to use hook.

---
This problem can be solved if ```RCLootCouncil:SendCommand``` also sends internal message (```AceEvent:SendMessage(message, ...)```)
```
currentAwardingGP = data and data.gp or 0
on_click()
      SendCommand("awarded",...)  
      OnMessageReceived() -- executed immediately after SendCommand only if SendCommand sends internal message.
          Award GP by currentAwardingGP -- Awarding 0 GP here.
    end
end
currentAwardingGP = 0
```

Example Change:
```
function RCLootCouncil:SendCommand(target, command, ...)
    self:SendMessage("RCSendCommand", target , command, ...)
        
    ...
end
```

**Comment by evil-morfar** [comment]
So what you're really trying to do, is confirm that the item has been awarded succcesfully, i.e. `ML:Award()` returns true. In that case, since you're using the original popup on_click, I could just let `RCLootCouncilML.AwardPopupOnClickYes` return the status of the award, and you could use that to call your own function directly.

**Comment by SafeteeWoW** [comment]
This is probably a better solution.

**Comment by evil-morfar** [comment]
It would at least clean up the code a bit. Included in the [latest commit](https://github.com/evil-morfar/RCLootCouncil2/commit/0379d1c36da8ab428b5911b390f5a2912e7eb442).

Also regarding versioning, I'm trying to stick to Semantic Versioning with a few exception (like in 2.6, hence the reason for this conversation) - i.e. all patch versions is fully backwards compatible bug fixes, and minor is new features that shouldn't break backwards compatibility (again except this one).

**Comment by evil-morfar** [comment]
Unfortunately returning the status from `ML:Award()` doesn't work, as the default LibDialog behavior is to only hide the dialog if the button function returns false as per line 511 in LibDialog-1.0.lua:
```lua
    if on_click then
        hide = not on_click(dialog, dialog.data, "clicked")
    end
```

I haven't found an alternative so far.

**Comment by SafeteeWoW** [comment]
Well, I think actually make some senses if on_click return status from ML:Award() and when returns true, dialog does not hide. (Return true = award fails. Return false = award success)

If the award fails, the dialog just stays there. This is a good notification to the user that the award fails.
Many times that I forget to keep the loot window opens and when I realize that, I have to open rightclick menu and dialog again. If you change the dialog in this way, I just need to click the dialog again.

```
function RCLootCouncilML.AwardPopupOnClickYes(frame, data)
	local awarded = RCLootCouncilML:Award(data.session, data.winner, data.responseID and addon:GetResponseText(data.responseID, data.isTierRoll, data.isRelicRoll), data.reason)
	...
	return not awarded -- Return true if award fails.
end
```

**Comment by SafeteeWoW** [comment]
Another Suggestion:
Change the Filter feature in the voting frame and history frame.

If the user don't know this feature and the filter is enabled by misclick, the user will be very likely be confused and assume RCLootCouncil is bugged. (Happened to me before)

I suggest you do ONE of the following:
1. When the voting frame or history frame open, print a message that tells the user which responses are currently filtered out and how to change the filter settings. (This is probably the easiest one to do.)
2. Reset the filter every time the voting frame or history frame opens.
3. Add a row at the bottom or top of the scrollTable that says "HOW MANY rows are hidden by filter".
4. The row is not completely hidden if filtered. Instead, it is showed at the bottom.
5. Display some text on the frame if some rows are filtered, or print a message in the ChatFrame.
6. Disable the filter feature.

**Comment by evil-morfar** [comment]
You might be right with the popup - but if it fails, it'll probably do it again the next time the user clicks "yes", leading to frutstration to why it won't go away. I can't really decide on that one - maybe it's just better to let it stay and add the error message to it.

New buttons are by default not filtered - people have to actually click the filter for any filtering to happen on anything - except when they receive the setttings from someone else; in that case it uses the original owners' filter settings.

Also I think it's very useful to hide non needed responses in a big raid, and I've had many requests to implement it and expand upon it through time. 

That being said, it might be nice to have some non intrusive text indicating a filter is active.

**Comment by SafeteeWoW** [comment]
I probably should just use ```lootTable[session].awarded```

But it creates problem when the user do award GP again when the item has been awarded.
In this case ```lootTable[session].awarded``` contains the winner name, but this award operation should fail.

I suggest to disable the rightclick menu when the item has been awarded.

**Comment by evil-morfar** [comment]
That also relies on comm messages though.
Edit: Well, the one from votingFrame does - the ML one doesn't. They are not the same! It seemed like a good idea at the time, but is honestly just bad design.

**Comment by SafeteeWoW** [comment]
so there are two different lootTables. One in RCLootCouncilML and the other in RCVotingFrame.
It seems that it is not good to use RCLootCouncilML.lootTable[session].awarded in votingFrame.

Can you fire a internal message when ```RCLootCouncilML:Award(session, winner, response, reason)``` returns? For, example
```
function RCLootCouncilML:Award(session, winner, response, reason)
        ...
                addon:SendMessage("RCAwardSuccess", session, winner, response, reason)
		return true
	
       ...

                addon:SendMessage("RCAwardFailed", session, winner, response, reason)
		return false
```

**Comment by evil-morfar** [comment]
The ML one is the initial one the ML creates with basicly only the items, while the votingFrame one is used, well, for the votingFrame, and also contains candidates along with their responses etc. 

That's probably the best way to do it.

**Comment by SafeteeWoW** [comment]
Can you add another field to RCVotingFrame.rightClickEntries and LootHistory.rightClickEntries?

```
-- hidden: [Boolean or function]
if (type(hidden)=='function' and hidden()) or (type(hidden)=='boolean' and hidden)
    Dont add the entry to the menu
end
```

I have found the way to get rid of dynamic stuff (Edited)

```
-- Refresh the content of first level of dropdown menu every 0.5s
local updateFrame = menu.RCEPGPUpdateFrame or CreateFrame("FRAME", "RCEPGPUpdateFrame"..menu:GetName(), menu)
menu.RCEPGPUpdateFrame = updateFrame
menu.RCEPGPUpdateFrame:SetScript("OnUpdate", function(self)
    if self.lastUpdateTime and GetTime() - self.lastUpdateTime < 0.5 then return end
    local menu = self:GetParent()
    if Lib_UIDropDownMenu_GetCurrentDropDown() ~= menu then return end
    if not Lib_DropDownList1:IsShown() then return end
    self.lastUpdateTime = GetTime()
    if menu.initialize then
        Lib_DropDownList1.numButtons = 0
        menu.initialize(menu, 1, menu.menuList)
    end
end)
```

This refresh the content of first level of rightclick menu every 0.5s and calls the initialization function and thus I can use your ```text``` field.

I just need that ```hidden``` field right now.


After all these changes, there are just several small hooks to RCVotingFrame:OnEnable() and RCLootCouncil:UpdateDB() left in the code. If you send internal message in these functions, I'll get rid of the hooks. (But probably no need to, as the hook is one line code).

**Comment by SafeteeWoW** [comment]
Some times ML:Award() returns true, but the award actually fails that the item is still in the loot window, such as when the awardee's bag is full.

Does RCLootCouncil check whether the award actually succeeds?

**Comment by evil-morfar** [comment]
I'll add the hidden field to 2.6 soon.

Doesn't recreating the entire dropdownmenu every ½ second cause performance issues? Couldn't you just update it when you have changes, i.e. when the user changes the gp value (not entirely sure what else could cause changes)? 

As for the ML:Award() return, it just returns true when it tries to hand out loot, as Blizzard's API doesn't allow me to track if the loot actually went out (as far as I know), and I haven't found a 100% reliable way to find out (without doing chat hooks). My best bet is rescan the lootlist and see if the awarded item is still in the same slot, but I'm not sure if it's reliable.

**Comment by SafeteeWoW** [comment]
I will update the menu only when there is changes. Update every 0.5s is a lazy way so I don't need to fire a callbacks for everything that could change the GP value.

You can catch ```LOOT_SLOT_CLEARED``` event to know if the item is awarded.
```LOOT_SLOT_CLEARED``` within a interval ---> award success
timeout  without ```LOOT_SLOT_CLEARED``` ---> award fails
But I can imagine you will need to make many changes for this.

**Comment by evil-morfar** [comment]
It should be relatively simple, and a lot cleaner than the current implementation.

I know about the `LOOT_SLOOT_CLEARED` but it doesn't really help much, as I would need to add several checks to make sure the slotIDs haven't changed, and the correct item actually was awarded, not to mention matching timers and filtering out any other slot changes. It would also leave `ML:Award()` with nothing to return. 

I think the simplest approach is to scan the lootList right after awarding the item, and if it's gone, it has been awarded. It would still need some extensive testing - I fear the item might not be awarded fast enough for such a check, in which case `LOOT_SLOOT_CLEARED` is probably the way to go.

Eitherway, it won't make it into v2.6.

**Comment by evil-morfar** [comment]
Also I expect to wrap up the remaining changes today, so hopefully we could go release for the next reset.

**Comment by evil-morfar** [comment]
To Recap
---
* Hidden field in rightclickmenus - [done](https://github.com/evil-morfar/RCLootCouncil2/commit/4bd57afec8525fbda164eea5d5c7f9e1102512c6)
* Messages in `ML:Award()` - [done](https://github.com/evil-morfar/RCLootCouncil2/commit/00975e5d82023c5f1911b7d34161b0f6cf919d73)

Both are currently untested.

---

* I'll consider the filter indicator for another update.
* Same goes for "proper award detection" as it's somewhat a lot of work.
* The popup changes will probably also be in another update.

I'm still [keeping](https://github.com/evil-morfar/RCLootCouncil2/commit/13c5def165b5cc5b2d748aba35c29347c19e0356) the todo's in core.lua, but I might switch to using GitHub issues and milestones at some point. I think that would make it easier for you (and potentially others) to keep up with future changes.

---
Let me know if I forgot something.

**Comment by SafeteeWoW** [comment]
Thanks. I will try to have the version that supports RCLootCouncil v2.6 ready before the next reset.

**Comment by SafeteeWoW** [comment]
Can you send internal messages when name or response changed in LootHistory frame?
Currently, I am hooking LootHistory:GetFrame().st:Refresh() to catch the changes.

**Comment by evil-morfar** [comment]
Sure - *what data do you need it to bring?*

Edit: [done](https://github.com/evil-morfar/RCLootCouncil2/commit/166d1558fa02387c1b0a2f15e892fd11d7c35731). I decided to just pass the data object, as you can extract everything from that.

Do you thing it'll be release ready tonight?

**Comment by SafeteeWoW** [comment]
Thanks. 
My coding part can be done tonight and need one extra day to do a final test.
Too many changes and new features in the new version.

**Comment by evil-morfar** [comment]
I'll postpone it till tomorrow then. You should probably consider just updating the 1.9 version to the changes if your 2.0 needs more testing.

**Comment by SafeteeWoW** [comment]
Sure. I'll work on that mini patch if v2.0 cant be done when RCLootCouncil v2.6 is released.

**Comment by SafeteeWoW** [comment]
Found a potential bug. In session 1, original award button does not give out item. It says "Cannot give item to guardian(player not in instance, ...)". Not sure the reason.

**Comment by SafeteeWoW** [comment]
Saved variable here:
https://gist.github.com/SafeteeWoW/28f46c9e02ad30da718a9331b2aa36c5

**Comment by SafeteeWoW** [comment]
I didn't find anything special in the SV. But the bug frequently occurs when I am in Session 1 when I clicked any award button in the rightclick menu. It seems like the name is recognized as "guardian", so the loot cant be distribute to "guardian"

**Comment by SafeteeWoW** [comment]
RCLootCouncilML:AnnounceAward is called without 5th argument "session". You are not using it and I don't need it either. I suggest you to get rid of it to avoid confusion.

**Comment by evil-morfar** [comment]
I'm not seeing any award attempts in your SV. I'm also not sure what you mean with your example.

Session not being included is an oversight on my end. I prefer to leave it in, as it's required to gather any other data from the voting frame, just in case someone doesn't store it.

**Comment by SafeteeWoW** [comment]
Could be a random bug or a bug on my end, because it does not happen on Wednesday.

**Comment by SafeteeWoW** [comment]
The release of RCLootCouncil-EPGP will be delayed because guild is adding days in order to kill M KJ.
I will push a beta version with some new feature incomplete if you release RCLootCouncil v2.6 on the weekend.

**Comment by SafeteeWoW** [comment]
https://github.com/SafeteeWoW/RCLootCouncil_EPGP/blob/648cccf221fbbbba33530d6ac08e8f69cb6a0325/lootHistory.lua#L226

I add a dialog in the rightclick menu of LootHistory that allows the user to edit the name by typing it.
This should partially solve the problem when the name list is too long.
If you would like to add it to RCLootCouncil v2.6, I will drop it from RCLootCouncil-EPGP.

**Comment by evil-morfar** [comment]
It makes somewhat sense to do (I did consider it), but the concern is if and when the game (as in what we read from it) can't differentiate between whatever the player wrote, and the actual player-realmname / GUID.  And honestly, it shouldn't be something that concerns EPGP. If makes sense to implement in RCLootCouncil, then please make a pull request with it implemented - otherwise it would be a feature of your own, that I couldn't possibly support.

And no, it wouldn't make the list shorter - it would  give you a reason not to look at the list.

**Comment by SafeteeWoW** [comment]
Pull request done:
https://github.com/evil-morfar/RCLootCouncil2/pull/17

**Comment by SafeteeWoW** [comment]
Found another issue.
```
function RCLootCouncil:CustomChatCmd(module, funcRef, helpString, ...)
	for i = 1, select("#", ...) do
		self.customChatCmd[select(i, ...)] = {module = module, func = funcRef}
	end
	L["chat_commands"] = L["chat_commands"] .."\n"..helpString
end
```
This could make L["chat_commands"]  a very long string when there are lots of chat commands.
WoW has issue to print a very long string that I cannot scroll the ChatFrame to see the top portion of the string.
The issue can be resolved if instead you are printing short string multiple times.


Store the helpstrings in a table and print them:
```
-- Line 461, core.lua
self:Print(L["chat_commands"])
for _, helpString in ipairs(self.customChatCmdHelpString) do
   print(helpString)
end

function RCLootCouncil:CustomChatCmd(module, funcRef, helpString, ...)
	for i = 1, select("#", ...) do
		self.customChatCmd[select(i, ...)] = {module = module, func = funcRef}
	end
       table.insert(self.customChatCmdHelpString, helpString)
end
```

**Comment by SafeteeWoW** [comment]
Another small request, can you add the following base item level information of the set token on normal difficulty in TokenInfo? Then I don't need to maintain another token info in RCLootCouncil-EPGP?

The pull request has been done.
https://github.com/evil-morfar/RCLootCouncil2/pull/18

**Comment by SafeteeWoW** [comment]
And if possible, can you add an internal message at the end of RCLootCouncil:UpdateDB()?

**Comment by evil-morfar** [comment]
Chat Commands
---
I didn't want to only make the modules' commands be single line printed, nor did I want to break the localizations done to the current chat commands, so I went for the next simplest approach: `gsub(L["chat_commands"], "(%C*)\n", print)` (plus some other small tweaks) which keeps the long string for storing the commands, but prints each line seperately. I'm not too sure how that handles non ascii characters though(!), but I think it should be fine.

I'll go for the table approach in a later update once the chat commands localization have had a chance to be updated.

Token info and rcmenu changes
---
I merged both in - the token ilvls could be handy for displaying the actual ilvl of the token when comparing - thanks.

I'm not a big fan of the newest entries being at the bottom - does the dropdown always grow up when it gets very big? Even when adding 20 tester entries mine only fills about 70% of the screen, and grows down where I normally have the loot history window.

It might be worth considering [LibQTip](https://www.wowace.com/projects/libqtip-1-0) - it seems to include scrollable dropdownmenus.

`UpdateDB()`
---
I included the message.

I'll probably do the 2.6 release tomorrow, as I'd like to have some time for potential bugfixes, which I won't have next week, and I don't want to wait another two weeks to release it.

**Comment by SafeteeWoW** [comment]
I don't like %C in gsub.
I prefer to write ```gsub(L["chat_commands"], "[^\n]+", print)``` 
and remove ```L["chat_commands"] = L["chat_commands"].."\n"```

---

RCMenu grows up for me, with about 100 entries. 
I debug it manipulating the number of entries displayed and I find that the menu always grow down if all entries can be displayed inside the screen and grow up otherwise.
I know this sorting is not a good solution when everything is inside the screen, but it is worse when the user is unable to change the name when there are too many names. I think it's a good trade-off.

However, this still does not always solve the problem. 
You might still consider to add a dialog to allow the user to enter the name manually.
The better solution might be only to show people eligible to receive this loot, but you'll have to record the list of raid members when the boss encounter starts, or when the RCLootCouncil session begins. (This might be a good thing to keep track of in the loot history, making RCLootCouncil an attendence tracker)

Anyway, I will drop the dialog to change the name in RCLootCouncil-EPGP, because I agree this should not exist in RCLootCouncil-EPGP

---
"LibQTip is designed replace GameTooltip". I doubt if it has a dropdownmenu.

---
I am still working on the new features and I am close to finish it.
But right now, I will get rid of it and make sure a new version of RCLootCouncil-EPGP is up ASAP.
I will release a new version soon after you release RCv2.6

**Comment by evil-morfar** [comment]
Didn't consider `gsub(L["chat_commands"], "[^\n]+", print)` - that's way better :)

---
I agree it's the best tradeoff right now.

My only problem with allowing the user to input a name is the amount of work involved in checking that name. It's fairly simple if the name is in the group or already in the history, but if not we'd have to either:

a) keep a log of every user (i.e. attendance tracking),
b) try to extract the name from the guild info, or
c) take whatever the user inputs, and try to match it up if we ever get the real name.

Users CAN NOT be trusted to input the correct names, so it would have to be checked either way - and it should have autocomplete to make it really useful. 

I'm also not keen on adding attendance tracking to RCLootCouncil either. At it's core, it's simply a tool to help managing a loot council. The scope of the project has already been widen enough in my opinion, which was part of the reason I made it more modular in v2.0 anyway. An attendance tracker should be a seperate module.

But maybe it doesn't need to be that complicated, and only allowing already recorded names might be good enough - eitherway I'll have to think about it, so it won't be in 2.6. If what you've done works, then just keep it in if you want.

---
Yeah it's a tooltip replacement, but it supports clicks (or at least `OnMouseDown`) on its lines, so it should be useable. The only other alternative I'm aware of is to build it ourselves using lib-st or similar.

**Comment by SafeteeWoW** [comment]
I think it is worthy to track the members eligible to receive the loot, even just for the loot council purpose.
When exported to excel or shown in the moreInfo of LootHistory, this information can be very useful.
And I find it is actually fairly simple
```
-- Insert in RCLootCouncil:TrackAndLogLoot
if not self.lootTable[session].bagged then
    local candidates = {}
    for i = 1, MAX_RAID_MEMBERS do
		local name, class, className = GetMasterLootCandidate(self.lootTable[session].lootSlot, i);
		if ( name ) then
                     table.insert(candidates, name)
		end
    end
    history_table["candidates"] = candidates
end
```

The concern is that this consumes significant amount of space and WoW do have an upper limit of the size of the Saved variable. I think history will consumes 50% more space after this change, but it probably fine.

---

"the token ilvls could be handy for displaying the actual ilvl of the token when comparing"
If I am wearing a 930 gear, while distributing a mythic Tier20 piece, gear difference should be 0.
Add this to your TODO list?

**Comment by SafeteeWoW** [comment]
The release of RCLootCouncil-EPGP should be ready if I find no issue in the raid starting right now.

**Comment by evil-morfar** [comment]
I don't see the need for it(?) unless you're interested in raid attendance. Also, it's even more simple than that, as all candidates are already stored in `addon.candidates`.

A full ToS clear would result in at least ~20 items - meaning it would store the same list of candidates at least 20 times. That's basically the definition of bad data structures :) Not to mention the added amount of data to send over comms (yes, it could be done locally). 

The "ideal" way to do it would be to register join/leave times for each raid, and extract the data from there on exports/other views, but it's still out of scope.

I'm pushing v2.6 soon.

**Comment by SafeteeWoW** [comment]
I have pushed too.
I have a question.
Are you also using CurseForge Repository? Is there any benefit using both CurseForge and Github repo?
I have tried to push into the CurseForge repo, but I have no idea what should be my username and password for the repo. I have logging into CurseForge through a Twitch account, but all name/password combination fails to push into the repo.

**Comment by evil-morfar** [comment]
Yes I am, but only because auto packaging from a remote repo wasn't a thing when I started, and I haven't dared changing it since. And there's no benefit afaik.

I'm not sure how the Twitch integration works with it, but if I remember correctly you need to use your Curse/Twitch email address as the username.

**Comment by SafeteeWoW** [comment]
Hi, can you change the ```history_table``` in ml_core.lua line 675 to ```RCLootCouncilML.history_table```, so I can add data into it?
I have the idea to store the GP value awarded for the item and display it in the LootHistory Frame.

I think this change is in-slope and don't have much side effects.

Planned usage:
```
if RCLootCouncilML.history_table then
   RCLootCouncilML.history_table["GP"] = gp
end
RCLootCouncilML.AwardPopupOnClickYes(self, data)
if RCLootCouncilML.history_table then
   RCLootCouncilML.history_table["GP"] = nil
end
```
Pull request done:
https://github.com/evil-morfar/RCLootCouncil2/pull/19

**Comment by SafeteeWoW** [comment]
I see most developers don't put the actual libs in the source code.
Instead, libs are included in .pkgmeta
For example, 
```
externals:
    libs/LibDialog:
        url: https://github.com/wildstarnasa/LibDialog.git
        tag: latest
```
Then the libraries included can be automatically updated by the author of the libraries.

The problem is you cant run your code without packaging it.
So there exists a script to generate packaged code without publish to Curseforge: See https://github.com/BigWigsMods/packager

I am going to follow this style and eliminate all libraries and localization strings in my source code

**Comment by evil-morfar** [comment]
The main reason I haven't done it is to have easy access to the libs from my IDE. Of course that could still be included, then ignored on build, and grapped from their sources. I just haven't bothered.

Alternatively one could also have the libs sitting in the interface/addons/rclootcouncil/libs folder, and just copy over the actual addon files.

As for localization - you should really keep your primary language file for easy updates to Curseforge. Otherwise you need to handle it all through Curseforge which is a pain imo.

**Comment by SafeteeWoW** [comment]
I have made a comment in evil-morfar/RCLootCouncil2#19

**Comment by SafeteeWoW** [comment]
Found that all source code that stores English localization on curseforge uses
```L[text] = text``` style, even if the text is very long.
But it does not make sense in my source code.
Probably should just store English locale in the source code.

**Comment by SafeteeWoW** [comment]
Finally, Mythic KJ is dead. Time to work on some new functionalities.

**Comment by SafeteeWoW** [comment]
Do you know if SendCommand is ordered?
If I send commands of A, B, C in order, is it guarantee that A is received before B, B is received before C, if no message is lost?

**Comment by evil-morfar** [comment]
I'm not sure what your point with the localization style is - that's just the way Ace3 handles localization which is what most addons use. Curseforge has support for multiple types of styles though.

Afaik commands are not guaranteed to be received in the order it's sent, but almost always will. RCLootCouncil v1.x required this, and I didn't encounter any problems I could trace back to this.

**Comment by SafeteeWoW** [comment]
Someone makes a suggestion that I should announce the GP value of the items when the session starts, but it seems not possible without rawhooking RCLootCouncilML:AnnounceItems() right now.

~~~Can you add replacement string(&n, &i, etc) into RCLootCouncilML:AnnounceItems() just like the announcement of the item award?~~~
Can you give me a way to add some text at the end of each chat message of RCLootCouncilML:AnnounceItems()

**Comment by evil-morfar** [comment]
Just check when the lootTable arrives or hook into `RCLootCouncilML:StartSession()`. That is unless you want to replace the output from :AnnounceItems(), which probably should be editable now that :AnnounceAward() is.

**Comment by SafeteeWoW** [comment]
I want to change the output of ```:AnnounceItems()```, dont think this is editable.
Will make a pull request for this.
