### ISSUE TITLE
Outsiders EPGP and RCLootCouncil_EPGP

### ISSUE THREAD

**Issue by Sammurph** [SafeteeWoW/RCLootCouncil_EPGP#2]
Dear Safetyy! :-)

Happy new Year!

We are using RCLootCouncil includin EPGP in our Raid. And it's awesome! Thank you 4 your great work! Well done! :-)
But we've got a small problem. We've got two outsiders in our Raid. They have a Twink in our Guild to safe the EPGP (incl. ext: in the officers-notes field) . in EPGP in can see their actuall Ratio/EP and GP. But not in RCLootCouncil.
Is there a way to fix this?
Thank you so much! :-)

**Comment by SafeteeWoW** [comment]
I'll try to fix this.

**Comment by SafeteeWoW** [comment]
What is "Twink"? Did you add some code to EPGP(DKP reloaded) to make it support outsiders?
There is no need to do that. EPGP(Dkp reloaded) has supported it. I think RCLootCouncil-EPGP does support the outsider feature of EPGP(dkp reloaded)

You need to:
1. Add ```@OUTSIDERS:1``` to the EPGP field of guild information
Example:
```
-EPGP-
@BASE_GP:4000
@DECAY_P:5
@MIN_EP:80000
@EXTRAS_P:100
@OUTSIDERS:1
-EPGP-
```
2. Write ```ext:OUTSIDERNAME```("ext" is case sensitive, no space after colon. OUTSIDERNAME is the full name of the outsider which includes realm name, case sensitive) in the **__public note__**( not officer note). The officer note will still contain EP/GP value.

**Comment by Sammurph** [comment]
Sorry...Twink is the german word vor an "Alt".

Thank you for your great support. 

We have all needs already done. But we din't attach the realm name. 

And now...after adding the Realm Name (e.g.: Limonade-Malyogs) ... it works PERFECT! Thank you very much!

**Comment by SafeteeWoW** [comment]
Resolved
