### ISSUE TITLE
GP not being awarded, taking away EP instead

### ISSUE THREAD

**Issue by aw021688** [SafeteeWoW/RCLootCouncil_EPGP#3]
Some members of my raid the addon is working as intended, but for about half of them the addon only takes away EP and doest add GP when awarding gear.  Help!
[RCLootCouncil.txt](https://github.com/SafeteeWoW/RCLootCouncil_EPGP/files/1646928/RCLootCouncil.txt)

**Comment by SafeteeWoW** [comment]
For some reason, "DKP mode" is enabled which converts GP operation into EP operations. Please disable that if you don't intend to do that.

P.S.: There is a confirmation dialog when you are attempting to enable "DKP mode". Not sure why that is enabled when you don't know what is "DKP mode"
